[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
cache = true
cache_path = "cache"
broadcast = "broadcast"
gas_reports = ["*"]
gas_reports_ignore = []
solc_version = "0.8.23"
optimizer = false
verbosity = 3
ignored_error_codes = []
block_number = 17_740_856
block_timestamp = 1_689_934_508

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15

[profile.production]
evm_version = "shanghai"
optimizer = true
optimizer_runs = 999999
build_info = true
sizes = true

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "https://rpc.sepolia.org"
